### ISSUE TITLE
Problem with HTML "" and removed success page

### ISSUE THREAD

**Issue by pedros89** [kurimawxx00/wifi-manager#1]
Hello,

I have created a new branch that easily allows you to customize the HTML:

`const char index_html[] PROGMEM = R"rawliteral(       put your custom HTML here        )rawliteral";`

This makes easy to add dynamic HTML variables such as %TEMPERATURE%

I made a new branch with all the modifications at:
https://github.com/pedros89/wifi-manager/tree/pedros89-patch-1

In addition I have made that the Webserver index page is reloaded every time user sends SSID and password. So basically there is no success page if credentials are already saved also Access Point is always on and the user can change SSID and password every time.

Feel free to watch the code and thank you very much for your starting point.

**Comment by rppelayo** [comment]
Marking this issue as solved. Thanks pedros89 for the contribution.
